//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyberMentor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CyberMentor.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New .
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        internal static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add DropOff.
        /// </summary>
        internal static string AddDropOff {
            get {
                return ResourceManager.GetString("AddDropOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Adertisments .
        /// </summary>
        internal static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Adv :.
        /// </summary>
        internal static string AdvDate {
            get {
                return ResourceManager.GetString("AdvDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area :.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in :.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number :.
        /// </summary>
        internal static string BuildingNumber {
            get {
                return ResourceManager.GetString("BuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card , Cash.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Type.
        /// </summary>
        internal static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed To Checkout.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Service.
        /// </summary>
        internal static string ChooseService {
            get {
                return ResourceManager.GetString("ChooseService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City :.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common User.
        /// </summary>
        internal static string CommonUser {
            get {
                return ResourceManager.GetString("CommonUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Booking.
        /// </summary>
        internal static string ConfirmBooking {
            get {
                return ResourceManager.GetString("ConfirmBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Passwrd.
        /// </summary>
        internal static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country :.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Country.
        /// </summary>
        internal static string CountryReg {
            get {
                return ResourceManager.GetString("CountryReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftman.
        /// </summary>
        internal static string Craftman {
            get {
                return ResourceManager.GetString("Craftman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CyberEvents.
        /// </summary>
        internal static string CyberEvents {
            get {
                return ResourceManager.GetString("CyberEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyber News.
        /// </summary>
        internal static string CyberNews {
            get {
                return ResourceManager.GetString("CyberNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyber Tube.
        /// </summary>
        internal static string CyberTube {
            get {
                return ResourceManager.GetString("CyberTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delievery Date.
        /// </summary>
        internal static string DelieveryDate {
            get {
                return ResourceManager.GetString("DelieveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destnation From :.
        /// </summary>
        internal static string DestnationFrom {
            get {
                return ResourceManager.GetString("DestnationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destnation To :.
        /// </summary>
        internal static string DestnationTo {
            get {
                return ResourceManager.GetString("DestnationTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please , Check Your Network Connection.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Products.
        /// </summary>
        internal static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Confirmation Code For.
        /// </summary>
        internal static string ForgetConfirmation {
            get {
                return ResourceManager.GetString("ForgetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Forget Password ?.
        /// </summary>
        internal static string ForgetPass {
            get {
                return ResourceManager.GetString("ForgetPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Have Account.
        /// </summary>
        internal static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, This Location doesn&apos;t have Address .
        /// </summary>
        internal static string LocationNotFound {
            get {
                return ResourceManager.GetString("LocationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Advertisment.
        /// </summary>
        internal static string MasterAddAdv {
            get {
                return ResourceManager.GetString("MasterAddAdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Policy.
        /// </summary>
        internal static string MasterAppLyc {
            get {
                return ResourceManager.GetString("MasterAppLyc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string MasterLogOut {
            get {
                return ResourceManager.GetString("MasterLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MasterNotification {
            get {
                return ResourceManager.GetString("MasterNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MasterSettings {
            get {
                return ResourceManager.GetString("MasterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPass {
            get {
                return ResourceManager.GetString("NewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t Have An Account.
        /// </summary>
        internal static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry There Are No Buildings In This Place Right Now Please Try Again Later !!.
        /// </summary>
        internal static string NoBuildings {
            get {
                return ResourceManager.GetString("NoBuildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        internal static string OldPass {
            get {
                return ResourceManager.GetString("OldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Service.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string PhoneCall {
            get {
                return ResourceManager.GetString("PhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickUp Location.
        /// </summary>
        internal static string PickUpLocation {
            get {
                return ResourceManager.GetString("PickUpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        internal static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Price :.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect Me.
        /// </summary>
        internal static string ProtectMe {
            get {
                return ResourceManager.GetString("ProtectMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty :.
        /// </summary>
        internal static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings :.
        /// </summary>
        internal static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Estate Marketer.
        /// </summary>
        internal static string RealEstateMarketer {
            get {
                return ResourceManager.GetString("RealEstateMarketer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        internal static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider.
        /// </summary>
        internal static string ServiceProvider {
            get {
                return ResourceManager.GetString("ServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Addresses.
        /// </summary>
        internal static string SettingsAddress {
            get {
                return ResourceManager.GetString("SettingsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Country And Language.
        /// </summary>
        internal static string SettingsCountry {
            get {
                return ResourceManager.GetString("SettingsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Personal Information.
        /// </summary>
        internal static string SettingsInfo {
            get {
                return ResourceManager.GetString("SettingsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string SettingsPass {
            get {
                return ResourceManager.GetString("SettingsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total :.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Advertisments.
        /// </summary>
        internal static string UserAdvs {
            get {
                return ResourceManager.GetString("UserAdvs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider.
        /// </summary>
        internal static string UserProvider {
            get {
                return ResourceManager.GetString("UserProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        internal static string ViewProfile {
            get {
                return ResourceManager.GetString("ViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Location.
        /// </summary>
        internal static string YourLocation {
            get {
                return ResourceManager.GetString("YourLocation", resourceCulture);
            }
        }
    }
}
